INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (1, 1, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (2, 2, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (3, 2, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (4, 3, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (5, 3, 3, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (6, 4, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (7, 4, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (8, 4, 4, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (9, 5, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (10, 5, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (11, 5, 5, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (12, 6, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (13, 6, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (14, 6, 6, 3, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (15, 6, 7, null, 3, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (16, 7, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (17, 8, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (18, 8, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (19, 9, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (20, 9, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (21, 9, 8, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (22, 10, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (23, 11, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (24, 11, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (25, 12, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (26, 12, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (27, 13, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (28, 13, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (29, 14, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (30, 14, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (31, 14, 7, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (32, 15, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (33, 15, 8, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (34, 15, 9, 2, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (35, 16, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (36, 17, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (37, 17, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (38, 18, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (39, 19, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (40, 19, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (41, 19, 6, 0, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (42, 20, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (43, 20, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (44, 20, 4, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (45, 21, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (46, 21, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (47, 21, 3, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (48, 22, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (49, 22, 6, 19, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (50, 22, 2, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (51, 23, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (52, 23, 6, 0, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (53, 24, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (54, 24, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (55, 25, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (56, 26, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (57, 27, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (58, 28, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (59, 29, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (60, 29, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (61, 30, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (62, 31, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (63, 31, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (64, 31, 8, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (65, 32, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (66, 32, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (67, 32, 6, 0, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (68, 33, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (69, 33, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (70, 34, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (71, 34, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (72, 35, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (73, 35, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (74, 36, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (75, 36, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (76, 37, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (77, 37, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (78, 38, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (79, 38, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (80, 39, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (81, 39, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (82, 40, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (83, 41, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (84, 42, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (85, 42, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (86, 43, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (87, 44, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (88, 45, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (89, 45, 8, 7, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (90, 46, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (91, 47, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (92, 48, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (93, 49, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (94, 49, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (95, 50, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (96, 50, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (97, 51, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (98, 52, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (99, 52, 8, 2, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (100, 53, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (101, 54, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (102, 55, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (103, 55, 6, 6, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (104, 56, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (105, 56, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (106, 56, 10, 1, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (107, 57, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (108, 58, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (109, 58, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (110, 59, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (111, 59, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (112, 60, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (113, 60, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (114, 61, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (115, 61, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (116, 62, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (117, 62, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (118, 62, 7, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (119, 63, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (120, 63, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (121, 64, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (122, 64, 12, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (123, 65, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (124, 65, 6, 1, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (125, 66, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (126, 67, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (127, 67, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (128, 68, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (129, 68, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (130, 69, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (131, 70, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (132, 70, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (133, 70, 3, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (134, 71, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (135, 71, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (136, 72, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (137, 72, 6, 17, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (138, 73, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (139, 73, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (140, 74, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (141, 74, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (142, 75, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (143, 76, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (144, 76, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (145, 76, 7, 2, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (146, 77, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (147, 78, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (148, 78, 6, 0, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (149, 78, 2, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (150, 79, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (151, 79, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (152, 80, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (153, 81, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (154, 82, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (155, 82, 3, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (156, 83, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (157, 83, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (158, 83, 6, 0, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (159, 84, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (160, 84, 8, 3, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (161, 84, 6, 8, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (162, 85, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (163, 85, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (164, 85, 9, 1, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (165, 86, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (166, 87, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (167, 87, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (168, 88, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (169, 88, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (170, 89, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (171, 89, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (172, 89, 6, 0, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (173, 90, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (174, 91, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (175, 91, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (176, 92, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (177, 93, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (178, 93, 7, 3, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (179, 94, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (180, 94, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (181, 95, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (182, 96, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (183, 96, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (184, 96, 3, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (185, 96, 5, null, 3, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (186, 97, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (187, 97, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (188, 98, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (189, 98, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (190, 99, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (191, 99, 6, 9, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (192, 100, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (193, 100, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (194, 101, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (195, 101, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (196, 101, 6, 0, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (197, 102, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (198, 102, 12, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (199, 102, 7, 2, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (200, 103, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (201, 104, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (202, 104, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (203, 104, 6, 0, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (204, 105, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (205, 105, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (206, 106, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (207, 107, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (208, 108, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (209, 109, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (210, 109, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (211, 109, 7, 2, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (212, 110, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (213, 111, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (214, 111, 7, 1, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (215, 112, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (216, 112, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (217, 113, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (218, 113, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (219, 113, 6, 0, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (220, 114, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (221, 114, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (222, 115, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (223, 115, 7, 1, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (224, 116, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (225, 116, 12, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (226, 116, 2, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (227, 117, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (228, 117, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (229, 118, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (230, 119, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (231, 119, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (232, 119, 6, 4, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (233, 120, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (234, 120, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (235, 121, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (236, 121, 6, 0, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (237, 121, 2, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (238, 122, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (239, 122, 13, 7, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (240, 123, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (241, 124, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (242, 124, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (243, 125, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (244, 126, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (245, 127, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (246, 127, 7, 1, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (247, 127, 2, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (248, 128, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (249, 128, 6, 0, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (250, 129, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (251, 129, 8, 2, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (252, 130, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (253, 130, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (254, 130, 6, 0, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (255, 131, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (256, 132, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (257, 132, 7, 0, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (258, 133, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (259, 133, 5, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (260, 134, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (261, 135, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (262, 136, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (263, 136, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (264, 136, 12, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (265, 137, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (266, 137, 15, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (267, 137, 2, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (268, 138, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (269, 138, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (270, 139, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (271, 140, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (272, 140, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (273, 141, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (274, 141, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (275, 141, 7, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (276, 142, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (277, 142, 15, 5, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (278, 143, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (279, 143, 12, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (280, 144, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (281, 144, 16, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (282, 145, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (283, 145, 6, 0, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (284, 146, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (285, 146, 6, 25, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (286, 147, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (287, 147, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (288, 148, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (289, 148, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (290, 149, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (291, 150, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (292, 150, 17, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (293, 150, 7, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (294, 151, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (295, 151, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (296, 151, 7, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (297, 152, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (298, 152, 6, 22, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (299, 152, 6, 2, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (300, 153, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (301, 153, 7, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (302, 153, 2, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (303, 154, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (304, 154, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (305, 154, 15, 4, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (306, 155, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (307, 155, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (308, 155, 8, 1, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (309, 156, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (310, 156, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (311, 156, 16, 1, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (312, 157, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (313, 157, 16, 1, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (314, 158, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (315, 158, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (316, 158, 13, 0, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (317, 159, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (318, 159, 2, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (319, 159, 16, null, 2, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (320, 160, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (321, 160, 7, null, 1, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (322, 161, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (323, 162, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (324, 163, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (325, 164, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (326, 165, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (327, 166, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (328, 167, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (329, 168, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (330, 169, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (331, 170, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (332, 171, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (333, 172, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (334, 173, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (335, 174, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (336, 175, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (337, 176, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (338, 177, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (339, 178, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (340, 179, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (341, 180, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (342, 181, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (343, 182, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (344, 182, 2, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (345, 183, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (346, 184, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (347, 185, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (348, 186, 2, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (349, 186, 1, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (350, 187, 1, null, 0, '2020-02-09 10:45:43', '2020-02-09 10:45:43');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (351, 186, 17, null, 0, null, null);
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (352, 188, 1, null, 0, '2020-02-15 11:00:21', '2020-02-15 11:00:21');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (353, 189, 1, null, 0, '2020-02-16 10:59:03', '2020-02-16 10:59:03');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (354, 190, 1, null, 0, '2020-02-18 11:21:56', '2020-02-18 11:21:56');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (355, 191, 1, null, 0, '2020-02-19 10:31:41', '2020-02-19 10:31:41');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (356, 192, 1, null, 0, '2020-02-19 19:02:00', '2020-02-19 19:02:00');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (357, 193, 1, null, 0, '2020-02-22 09:10:30', '2020-02-22 09:10:30');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (358, 194, 1, null, 0, '2020-02-25 13:40:01', '2020-02-25 13:40:01');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (359, 195, 1, null, 0, '2020-02-26 10:30:42', '2020-02-26 10:30:42');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (360, 196, 1, null, 0, '2020-02-28 08:48:06', '2020-02-28 08:48:06');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (361, 197, 1, null, 0, '2020-03-02 08:41:14', '2020-03-02 08:41:14');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (362, 197, 2, null, 0, '2020-03-02 08:41:29', '2020-03-02 08:41:29');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (363, 198, 2, null, 0, '2020-03-04 08:59:51', '2020-03-04 08:59:51');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (364, 199, 1, null, 0, '2020-03-06 10:59:56', '2020-03-06 10:59:56');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (365, 200, 1, null, 0, '2020-03-07 11:22:51', '2020-03-07 11:23:56');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (366, 201, 1, null, 0, '2020-03-10 12:05:26', '2020-03-10 12:05:26');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (367, 202, 1, null, 0, '2020-03-10 12:09:41', '2020-03-10 12:09:41');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (368, 203, 1, null, 0, '2020-03-19 18:08:30', '2020-03-19 18:08:30');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (369, 204, 1, null, 0, '2020-03-22 13:06:08', '2020-03-22 13:06:08');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (370, 205, 1, null, 0, '2020-03-24 12:04:21', '2020-03-24 12:04:21');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (371, 206, 1, null, 0, '2020-03-27 08:11:08', '2020-03-27 08:11:08');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (372, 194, 17, 2, 0, '2020-04-23 08:00:38', '2020-04-23 08:00:38');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (373, 207, 1, null, 0, '2020-05-06 18:40:28', '2020-05-06 18:40:28');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (374, 208, 2, null, 0, '2020-05-11 18:00:46', '2020-05-11 18:00:46');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (375, 209, 1, null, 0, '2020-05-12 18:43:47', '2020-05-12 18:43:47');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (376, 210, 1, null, 0, '2020-05-14 08:03:53', '2020-05-14 08:03:53');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (377, 211, 1, null, 0, '2020-08-24 17:14:45', '2020-08-24 17:14:45');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (378, 212, 1, null, 0, '2021-05-17 21:13:15', '2021-05-17 21:13:15');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (379, 213, 1, null, 0, '2021-07-18 07:44:13', '2021-07-18 07:44:13');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (380, 214, 7, 1, 0, '2021-08-19 07:34:05', '2021-08-19 07:34:05');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (381, 216, 1, null, 0, '2021-10-12 20:15:44', '2021-10-12 20:15:44');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (382, 217, 1, null, 0, '2021-10-19 22:13:36', '2021-10-19 22:13:36');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (384, 218, 2, null, 0, '2021-11-30 16:57:16', '2021-11-30 16:57:16');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (385, 220, 1, null, 0, '2022-01-26 14:22:32', '2022-01-26 14:22:32');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (386, 221, 1, null, 0, '2022-01-26 14:22:42', '2022-01-26 14:22:42');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (387, 219, 1, null, 0, '2022-01-26 14:22:50', '2022-01-26 14:22:50');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (388, 222, 1, null, 0, '2022-01-26 14:22:59', '2022-01-26 14:22:59');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (389, 222, 2, null, 0, '2022-01-26 14:23:13', '2022-01-26 14:23:13');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (390, 222, 3, null, 0, '2022-01-26 14:23:27', '2022-01-26 14:23:27');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (391, 223, 1, null, 0, '2022-01-26 14:23:36', '2022-01-26 14:23:36');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (392, 224, 1, null, 0, '2022-01-26 14:23:44', '2022-01-26 14:23:44');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (393, 224, 2, null, 0, '2022-01-26 14:23:57', '2022-01-26 14:23:57');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (394, 225, 1, null, 0, '2022-01-26 14:24:05', '2022-01-26 14:24:05');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (395, 226, 1, null, 0, '2022-01-26 14:24:13', '2022-01-26 14:24:13');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (396, 227, 1, null, 0, '2022-01-26 14:24:27', '2022-01-26 14:24:27');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (397, 227, 2, null, 0, '2022-01-26 14:24:48', '2022-01-26 14:24:48');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (398, 228, 1, null, 0, '2022-01-26 14:25:00', '2022-01-26 14:25:00');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (399, 228, 2, null, 0, '2022-01-26 14:25:11', '2022-01-26 14:25:11');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (400, 229, 1, null, 0, '2022-01-26 14:25:27', '2022-01-26 14:25:27');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (401, 230, 1, null, 0, '2022-01-26 14:27:43', '2022-01-26 14:27:43');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (402, 231, 1, null, 0, '2022-01-26 14:27:50', '2022-01-26 14:27:50');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (403, 232, 1, null, 0, '2022-01-26 14:27:56', '2022-01-26 14:27:56');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (404, 235, 1, null, 0, '2022-09-14 20:04:52', '2022-09-14 20:04:52');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (405, 235, 2, null, 0, '2022-09-14 20:05:05', '2022-09-14 20:05:05');
INSERT INTO boomclone.level_target (id, level_id, target_id, target_amount, `order`, created_at, updated_at) VALUES (406, 235, 5, null, 0, '2022-09-14 20:05:22', '2022-09-14 20:05:22');
