INSERT INTO boomclone.targets (id, type, created_at, updated_at) VALUES (1, 'Fastest time', null, null);
INSERT INTO boomclone.targets (id, type, created_at, updated_at) VALUES (2, 'All pickups', null, null);
INSERT INTO boomclone.targets (id, type, created_at, updated_at) VALUES (3, 'Complete Right Button', null, null);
INSERT INTO boomclone.targets (id, type, created_at, updated_at) VALUES (4, 'No coins', null, null);
INSERT INTO boomclone.targets (id, type, created_at, updated_at) VALUES (5, 'All bombs', null, null);
INSERT INTO boomclone.targets (id, type, created_at, updated_at) VALUES (6, 'Pickups', null, null);
INSERT INTO boomclone.targets (id, type, created_at, updated_at) VALUES (7, 'Touch ball', null, null);
INSERT INTO boomclone.targets (id, type, created_at, updated_at) VALUES (8, 'Bombs', null, null);
INSERT INTO boomclone.targets (id, type, created_at, updated_at) VALUES (9, 'Rockets', null, null);
INSERT INTO boomclone.targets (id, type, created_at, updated_at) VALUES (10, 'Use rocket', null, null);
INSERT INTO boomclone.targets (id, type, created_at, updated_at) VALUES (11, 'Only one rocket', null, null);
INSERT INTO boomclone.targets (id, type, created_at, updated_at) VALUES (12, 'Finish with rocket', null, null);
INSERT INTO boomclone.targets (id, type, created_at, updated_at) VALUES (13, 'Springboards', null, null);
INSERT INTO boomclone.targets (id, type, created_at, updated_at) VALUES (14, 'All jumpboards', null, null);
INSERT INTO boomclone.targets (id, type, created_at, updated_at) VALUES (15, 'Touch star', null, null);
INSERT INTO boomclone.targets (id, type, created_at, updated_at) VALUES (16, 'Break ball', null, null);
INSERT INTO boomclone.targets (id, type, created_at, updated_at) VALUES (17, 'Touch bowling pin', null, null);
